volumes:
  labmc_data:

services:
  postgres:
    container_name: labmc_postgres
    hostname: postgres
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: 'labmc'
      POSTGRES_USER: 'labmc'
      POSTGRES_PASSWORD: 'labmc'
    ports:
      - 5432:5432
    volumes:
      - labmc_data:/var/lib/postgresql/data
    networks:
      - labmc

networks:
  labmc:
